name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run TypeScript compiler
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Check for forbidden file modifications
      if: github.event_name == 'pull_request'
      run: |
        # Check if any protected files were modified
        PROTECTED_FILES=$(git diff --name-only origin/main...HEAD | grep -E '^(supabase/|\.env|src/lib/supabase\.ts|src/lib/payments\.ts)' || true)
        
        if [ ! -z "$PROTECTED_FILES" ]; then
          echo "❌ ERROR: Protected files were modified:"
          echo "$PROTECTED_FILES"
          echo ""
          echo "These files are part of the payment spine and must not be modified."
          echo "Please revert changes to these files."
          exit 1
        fi
        
        echo "✅ No protected files modified"
    
    - name: Lint check (optional)
      run: npm run lint || true
      continue-on-error: true